import React from "react";
import { Brain, Zap, Users, Award, Sparkles } from "lucide-react";
function About() {
  return (
    <div className="bg-gray-50 dark:bg-gray-900 text-gray-800 dark:text-gray-200">
      {/* Hero Section */}
      <section className="relative py-20 text-center px-6 bg-gradient-to-r from-indigo-500 via-purple-500 to-gray-500 text-white">
        <h1 className="text-5xl font-extrabold mb-4">About SmartQuiz AI</h1>
        <p className="max-w-2xl mx-auto text-lg opacity-90">
          SmartQuiz AI is an intelligent quiz platform powered by AI. Learn
          smarter, test faster, and get personalized insights instantly.
        </p>
      </section>

      {/* Mission Section */}
      <section className="py-16 max-w-5xl mx-auto px-6 text-center">
        <h2 className="text-3xl font-bold mb-6">Our Mission</h2>
        <p className="text-lg text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
          Our mission is to revolutionize learning by making quizzes adaptive,
          fun, and powered by the latest AI technology. Whether you are a
          student, teacher, or lifelong learner — SmartQuiz AI is designed for
          you.
        </p>
      </section>

      {/* Features Section */}
      <section className="py-16 bg-gray-100 dark:bg-gray-800">
        <div className="max-w-6xl mx-auto px-6">
          <h2 className="text-3xl font-bold text-center mb-12">
            Why Choose SmartQuiz AI?
          </h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            <FeatureCard
              icon={<Brain className="w-10 h-10 text-indigo-500" />}
              title="AI-Powered"
              description="Get smart quizzes generated by AI based on your learning style."
            />
            <FeatureCard
              icon={<Zap className="w-10 h-10 text-yellow-500" />}
              title="Instant Feedback"
              description="Receive real-time performance analysis and suggestions."
            />
            <FeatureCard
              icon={<Award className="w-10 h-10 text-green-500" />}
              title="Gamified Learning"
              description="Earn points, badges, and climb the leaderboard while learning."
            />
            <FeatureCard
              icon={<Users className="w-10 h-10 text-pink-500" />}
              title="Community Driven"
              description="Join a community of learners, share quizzes, and grow together."
            />
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-16 max-w-5xl mx-auto px-6">
        <h2 className="text-3xl font-bold text-center mb-12">How It Works</h2>
        <div className="grid md:grid-cols-3 gap-8 text-center">
          <StepCard
            step="1"
            title="Choose a Topic"
            description="Pick any subject or let AI suggest based on your learning history."
          />
          <StepCard
            step="2"
            title="Take Quiz"
            description="Answer AI-generated questions tailored to your skill level."
          />
          <StepCard
            step="3"
            title="Get Insights"
            description="Instant feedback with detailed explanations and next steps."
          />
        </div>
      </section>

      {/* Call To Action */}
      <section className="py-20 text-center bg-gradient-to-r from-indigo-600 to-purple-600 text-white">
        <h2 className="text-4xl font-bold mb-4">
          Ready to Boost Your Learning?
        </h2>
        <p className="mb-8 text-lg opacity-90">
          Start your journey with SmartQuiz AI and transform the way you study.
        </p>
        <button className="px-8 py-3 bg-white text-indigo-600 font-semibold rounded-xl shadow-lg hover:bg-gray-100 transition">
          Get Started
        </button>
      </section>
    </div>
  );
}

/* Components */
function FeatureCard({ icon, title, description }) {
  return (
    <div className="bg-white dark:bg-gray-900 rounded-2xl shadow-lg p-6 text-center hover:scale-105 transition-transform">
      <div className="flex justify-center mb-4">{icon}</div>
      <h3 className="text-xl font-semibold mb-2">{title}</h3>
      <p className="text-gray-600 dark:text-gray-400">{description}</p>
    </div>
  );
}

function StepCard({ step, title, description }) {
  return (
    <div className="bg-white dark:bg-gray-900 rounded-2xl shadow-lg p-6 hover:scale-105 transition-transform">
      <div className="text-3xl font-extrabold text-indigo-500 mb-4">{step}</div>
      <h3 className="text-xl font-semibold mb-2">{title}</h3>
      <p className="text-gray-600 dark:text-gray-400">{description}</p>
    </div>
  );
}

export default About;
