import React from "react";
import { Brain, Zap, Award, Users } from "lucide-react";

function HomePage() {
  return (
    <div className="bg-gray-50 dark:bg-gray-900 text-gray-800 dark:text-gray-200">
      {/* Hero Section */}
      <section className="relative py-20 text-center px-6 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 text-white">
        <h1 className="text-5xl font-extrabold mb-6 leading-tight">
          Master Learning with{" "}
          <span className="text-yellow-300">SmartQuiz AI</span>
        </h1>
        <p className="max-w-2xl mx-auto text-lg opacity-90 mb-8">
          AI-powered quizzes that adapt to your knowledge level. Learn smarter,
          test faster, and grow with personalized insights.
        </p>
        <div className="flex justify-center gap-4">
          <a
            href="#get-started"
            className="px-6 py-3 bg-white text-indigo-600 font-semibold rounded-xl shadow hover:bg-gray-100 transition"
          >
            Get Started
          </a>
          <a
            href="#learn-more"
            className="px-6 py-3 border border-white text-white font-semibold rounded-xl hover:bg-white hover:text-indigo-600 transition"
          >
            Learn More
          </a>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 bg-gray-100 dark:bg-gray-800">
        <div className="max-w-6xl mx-auto px-6 text-center">
          <h2 className="text-3xl font-bold mb-12">Why SmartQuiz AI?</h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            <FeatureCard
              icon={<Brain className="w-10 h-10 text-indigo-500" />}
              title="AI-Powered"
              description="Quizzes generated by AI to match your learning style."
            />
            <FeatureCard
              icon={<Zap className="w-10 h-10 text-yellow-500" />}
              title="Instant Feedback"
              description="Real-time analysis with detailed performance reports."
            />
            <FeatureCard
              icon={<Award className="w-10 h-10 text-green-500" />}
              title="Gamified Learning"
              description="Earn badges, compete, and make learning fun."
            />
            <FeatureCard
              icon={<Users className="w-10 h-10 text-pink-500" />}
              title="Community Driven"
              description="Join learners worldwide, share and challenge quizzes."
            />
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-16 max-w-6xl mx-auto px-6">
        <h2 className="text-3xl font-bold text-center mb-12">How It Works</h2>
        <div className="grid md:grid-cols-3 gap-8 text-center">
          <StepCard
            step="1"
            title="Choose a Topic"
            description="Pick a subject or let AI recommend based on your history."
          />
          <StepCard
            step="2"
            title="Take the Quiz"
            description="Answer smart AI-generated questions tailored to you."
          />
          <StepCard
            step="3"
            title="Get Insights"
            description="Receive instant feedback with personalized study tips."
          />
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 text-center bg-gradient-to-r from-indigo-600 to-purple-600 text-white">
        <h2 className="text-4xl font-bold mb-4">
          Ready to Level Up Your Learning?
        </h2>
        <p className="mb-8 text-lg opacity-90">
          Start your SmartQuiz AI journey today and unlock your full potential.
        </p>
        <button className="px-8 py-3 bg-white text-indigo-600 font-semibold rounded-xl shadow-lg hover:bg-gray-100 transition">
          Start Now
        </button>
      </section>
    </div>
  );
}

/* Reusable Components */
function FeatureCard({ icon, title, description }) {
  return (
    <div className="bg-white dark:bg-gray-900 rounded-2xl shadow-lg p-6 text-center hover:scale-105 transition-transform">
      <div className="flex justify-center mb-4">{icon}</div>
      <h3 className="text-xl font-semibold mb-2">{title}</h3>
      <p className="text-gray-600 dark:text-gray-400">{description}</p>
    </div>
  );
}

function StepCard({ step, title, description }) {
  return (
    <div className="bg-white dark:bg-gray-900 rounded-2xl shadow-lg p-6 hover:scale-105 transition-transform">
      <div className="text-3xl font-extrabold text-indigo-500 mb-4">{step}</div>
      <h3 className="text-xl font-semibold mb-2">{title}</h3>
      <p className="text-gray-600 dark:text-gray-400">{description}</p>
    </div>
  );
}

export default HomePage;
